---
title: "TASSEL Phenotype PCA summary"
author: "Katie Lotterhos"
date: "May 26, 2015"
output: html_document
---

The following code and datasets were sent to me by Haktan:

```{r}
setwd("/Users/katie/Desktop/current projects/1-AdaptreeData/2015_POST_FILTERING/pine_data/phenotypes")
source("PCACodeForKatie.R")
ls()
```

The PCA output is in the variable *pc*
```{r}
str(pc)
barplot(pc$sdev, ylab="Standard Deviation", names.arg = 1:17, xlab="PC axis")

loadings <- pc$rotation
dim(loadings)
par(mfcol=c(2,2), mar=c(4,4,1,1))
  ### Left column
  plot(loadings[,1], loadings[,2], xlab="PC1", ylab="PC2", col=0, bty="l")
  text(loadings[,1], loadings[,2], rownames(loadings), cex=0.7)
  plot(loadings[,1], loadings[,3], xlab="PC1", ylab="PC3", col=0, bty="l", xlim=c(-0.5,0.4))
  text(loadings[,1], loadings[,3], rownames(loadings), cex=0.7)

  ### Right column
  plot(loadings[,1], loadings[,4], xlab="PC1", ylab="PC4", col=0, bty="l", xlim=c(-0.5,0.4))
  text(loadings[,1], loadings[,4], rownames(loadings), cex=0.7)
  plot(loadings[,1], loadings[,5], xlab="PC1", ylab="PC5", col=0, bty="l", xlim=c(-0.5,0.4))
  text(loadings[,1], loadings[,5], rownames(loadings), cex=0.7)
```

Note that the y-axis in the following graphs are meaningless, phenotypes are just stacked for easy readability.


```{r}
  par(mfrow=c(1,1), mar=c(4,0,0,0))
  makePCplot <- function(pc){
    plot(loadings[,pc], (rank(loadings[,pc])), bty="l", yaxt="n", ylab="", xlab=paste("PC", pc), col=0, xlim=c(-1,1))
    text(loadings[,pc], (rank(loadings[,pc])), rownames(loadings))
  }
  for (i in c(1:5, 8, 11, 13)){
  makePCplot(i)
  }
```

